services:
  - type: web
    name: ai-resume-screening
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn App:app --bind 0.0.0.0:$PORT --workers 1 --timeout 180"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: uploads
      - key: GEMINI_API_KEY
        sync: false
      - key: MAIL_SENDER
        sync: false
      - key: MAIL_PASSWORD
        sync: false
        key: DATABASE_URL
        value: postgresql://postgres.lhyzjkegabkthrjzahpq:yxJ9bF637uKSrQaf@aws-0-ap-south-1.pooler.supabase.com:5432/postgres
